
############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置，dev：开发环境，test：测试环境，prod：生产环境
  application:
    name: apusic-demo
  datasource:                                         # 数据源的相关配置
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/TEST?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: 123456789
